store/main/urls.py
from django.urls import path
from main import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from store import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    #path("__debug__/", include("debug_toolbar.urls")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]
#для отладки запросов к БД
if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path
from users import views
app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

store/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = "Пользователи"
    def __str__(self):
        return self.username

store/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User

class UserLoginForm(AuthenticationForm):

    #переопрделим стандартные поля формы
    # username = forms.CharField(
    #     label = 'Имя',
    #     widget = forms.TextInput(attrs={"autofocus": True, 
    #                                 'class': 'form-control',
    #                                 'placeholder': 'Введите ваше имя пользователя'})
    # )
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget = forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                 'class': 'form-control',
    #                                 'placeholder': 'Введите ваш пароль'})
    # )
    #Укороченный вариант
    username = forms.CharField()
    password = forms.CharField()
    #вложенный класс для полей авторизации
    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

store/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib import auth, messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from carts.models import Cart
from orders.models import Order, OrderItem
from django.db.models import Prefetch

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            #сессионный ключ неавторизованного пользователя
            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                #уведомление пользователя о входе
                messages.success(request, f"{username}, успешно вошел на сайт")

                #когда авторизуется пользователь с заполненной корзиной по сессионном ключу то привязываем ему корзину
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                #редирект для неавторизованного пользователя
                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            #сессионный ключ неавторизованного пользователя
            session_key = request.session.session_key
            #записываем в переменную введенные при регистрации данные
            user = form.instance
            #делаем автовход по сохраненным из формы регистрации данным
            auth.login(request, user)

            #когда регистрируется и авторизуется пользователь с заполненной корзиной по сессионном ключу то привязываем ему корзину
            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f"{user.username}, успешно зарегистрировался и вошел на сайт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Home - Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

#ограничение доступа для неавторизованных пользователей
@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Пользователь упешно обновлен")
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        #отображение информации пользователя
        form = ProfileForm(instance=request.user)
    
    #отображение заказов в профиле
    orders = (
        #фильтруем заказы по пользователю
        Order.objects.filter(user=request.user).prefetch_related(
            #класс prefetch - указываем имя дополнительного queryset и формируем его из всех заказов по пользователю и через select_releted всеми товарами привязанными к этим заказам
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        )
        #сортируем полученные элементы по -id - вверху будет последний заказ
        .order_by("-id")
    )
    context = {
        'title': 'Home - Кабинет',
        'form': form,
        'orders': orders,
    }
    return render(request, 'users/profile.html', context)

def users_cart(request):
    return render(request, "users/users_cart.html")

#ограничение доступа для неавторизованных пользователей
@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, упешно вышел")
    auth.logout(request)
    return redirect(reverse('main:index'))

store/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% comment %} расширяем базовый шаблон кнопкой корзины {% endcomment %}
{% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        {% comment %} Редирект для неавторизованного пользователя когда сработал декоратор {% endcomment %}
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value={{ request.GET.next }}>
                        {% endif %}
                        {% comment %} реализация формы входа на сайт с минимальным обращением к бэкенду {% endcomment %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" 
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                            name="username" id="id_username" 
                            placeholder="Введите ваше имя пользователя" 
                            required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" 
                            name="password" id="id_password" 
                            placeholder="Введите ваш пароль" 
                            required>
                        </div>


                        {% comment %} {% for item in form %}
                            <div class="mb-3">
                                <label for="{{ item.id_for_label }}" class="form-label">{{ item.label }}</label>
                                {{ item }}
                            </div>
                        {% endfor %} {% endcomment %}


                        {% comment %} <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
                            {{ form.password }}
                        </div> {% endcomment %}


                        {% comment %} <div class="mb-3">
                            <label for="username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                        </div>{% endcomment %}
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href="{% url 'user:registration' %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

store/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}
{% comment %} расширяем базовый шаблон кнопкой корзины {% endcomment %}
{% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{% url 'user:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                    name="first_name"
                                    placeholder="Введите ваше имя" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя" required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                    name="email"
                                    placeholder="Введите ваш email" required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" id="id_password1"
                                    value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                    name="password1"
                                    placeholder="Введите пароль" required>
                                    {% if form.password1.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" id="id_password2"
                                    value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                    name="password2"
                                    placeholder="Подтвердите пароль" required>
                                    {% if form.password2.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

store/users/templates/users/users_cart.html
{% extends 'base.html' %}
{% load static %}
{% comment %} подключаем шаблонный тег из приложения carts для передачи карзин пользователя {% endcomment %}
{% load carts_tags %}

{% block content %}
{% comment %} подключаем шаблонный тег из приложения carts для передачи карзин пользователя {% endcomment %}
{% user_carts request as carts %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "carts/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                    {% comment %} {% if carts %}
                        <a class="btn btn-dark" href="../orders/create_order.html">
                            Оформить заказ
                        </a>
                    {% endif %} {% endcomment %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}